config/routes.rb
Rails.application.routes.draw do
  get 'yaml_samples/new'

  resources :yaml_samples

  root 'yaml_samples#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/yaml_sample.rb
class YamlSample
  include ActiveModel::Model
  attr_accessor :text

  def initialize(text)
    @text = text
  end

  # Validates the syntax of the YAML.
  # Returns a hash containing information about the first error found when
  # parsing the YAML, or nil if no errors are found.
  def errors
    yaml_errors = nil
    begin
      YAML.safe_load(@text)
    rescue Psych::SyntaxError => e
      yaml_errors = {
        line: e.line,
        column: e.column,
        message: e.message
      }
    end
    yaml_errors
  end

  # Determine the locale of the YAML.
  # Based off of rails i18n YAML file structure where the first key
  # is the locale.
  # Returns a symbol of the samples locale, or nil if the yaml is invalid.
  def locale
    return nil if errors

    locale = YAML.safe_load(@text).keys.first
    locale.to_sym
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/yaml_samples_controller.rb
require 'zip'

class YamlSamplesController < ApplicationController
  def create
    if yaml_sample_params[:text]
      create_from_text
    elsif yaml_sample_params[:file]
      file_type = yaml_sample_params[:file].content_type
      logger.info file_type
      if file_type == "application/zip"
        create_from_zip_file
      elsif
        create_from_yaml_file
      end
    end
  end

  def create_from_text
    @yaml_sample = YamlSample.new(yaml_sample_params[:text])
    render @yaml_sample
  end

  def create_from_yaml_file
    yaml_text = yaml_sample_params[:file].read
    @yaml_sample = YamlSample.new(yaml_text)
    render @yaml_sample
  end

  def create_from_zip_file
    Zip::File.open(yaml_sample_params[:file].open) do |zip_file|
      @yaml_samples = []
      zip_file.each do |yaml_file|
        # Move to next file if it's a directory, not a .yml file, or one of the funky osx files
        if yaml_file.ftype == :directory ||
           !yaml_file.name.match?(/(.yml)\z/) ||
           yaml_file.name.match?(/\A(__MACOSX)/)
          next
        end
        yaml_text = yaml_file.get_input_stream.read
        @yaml_samples << YamlSample.new(yaml_text)
      end
    end
    render "yaml_samples"
  end

  private

  def yaml_sample_params
    params.require(:yaml_sample).permit(:text, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yaml_samples_helper.rb
module YamlSamplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yamlator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/yaml_samples/_yaml_sample.html.erb
<%= javascript_include_tag('lang-yaml.js') %>
<%= javascript_include_tag('prettify.js') %>
<%= stylesheet_link_tag('prettify.css') %>

<body onload="PR.prettyPrint()">
<pre class="prettyprint linenums lang-yaml"><%= @yaml_sample.text %></pre>
<p>
  <%= @yaml_sample.errors %>
</p>

app/views/yaml_samples/new.html.erb
<h1><%= I18n.t('title') %></h1>
<p>
  Enter YAML text to lint:
</p>
<%= form_with scope: :yaml_sample, url: yaml_samples_path, local: true do |form| %>
  <p>
    <%= form.text_area :text, placeholder: t("sample.text_entry_placeholder") %>
  </p>
  <p>
    <%= form.submit "Submit YAML Text"%>
  </p>
<% end %>
<p>
  Or, submit a YAML file or a ZIP file to be linted:
</p>
<%= form_with scope: :yaml_sample, url: yaml_samples_path, local: true do |form| %>
  <p>
    <%= form.file_field :file %>
  </p>
  <p>
    <%= form.submit "Submit a File" %>
  </p>
<% end %>

app/views/yaml_samples/yaml_samples.html.erb
<%= javascript_include_tag('lang-yaml.js') %>
<%= javascript_include_tag('prettify.js') %>
<%= stylesheet_link_tag('prettify.css') %>

<body onload="PR.prettyPrint()">
<% @yaml_samples.each do |sample| %>
  <pre class="prettyprint linenums lang-yaml"><%= sample.text %></pre>
  <p>
    <%= sample.errors %>
  </p>
<% end %>